name: substore_app
description: Substore app
version: 1.3.0+9
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: 3.29.2

dependencies:
  bloc: 8.1.1
  dio: 5.4.1
  equatable: ^2.0.5
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.2
  flutter_dotenv: 5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^8.1.0
  get_it: 7.6.4
  go_router: ^13.2.1
  google_fonts: 6.1.0
  intl: 0.19.0  
  json_annotation: ^4.8.1
  mobile_scanner: ^5.0.1
  package_info_plus: ^8.1.1
  qr_flutter: ^4.1.0
  screen_brightness: ^1.0.0
  shimmer: 3.0.0
  socket_io_client: 2.0.3+1
  uni_links: ^0.5.1
  url_launcher: ^6.2.6
  wakelock_plus: 1.2.8

dev_dependencies:
  bloc_test: 9.1.7
  build_runner: ^2.4.8
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: 0.3.0
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - envs/
    - assets/images/

flutter_native_splash:
  image: assets/images/substore_logo.png
  color: "#ffffff"
  web: false
